{{ if eq .Values.clusterType "kubernetes" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.wes.appName }}
  name: {{ .Values.wes.appName }}
spec:
  rules:
  - host: {{ .Values.wes.appName }}.{{ .Values.applicationDomain }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ .Values.wes.appName }}
          servicePort: 8080
{{ else }} # assume OpenShift by default
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.wes.appName }}
spec:
  host: {{ .Values.wes.appName }}.{{ .Values.applicationDomain }}
  to:
    kind: Service
    weight: 100
    name: {{ .Values.wes.appName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
status: 
  ingress: []
{{ end }}

