---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.wes.appName }}-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '1Gi' # TODO template this
