# Default values for protes_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationDomain: c03.k8s-popup.csc.fi
clusterType: kubernetes

wes:
  appName: wes
  image: weselixir/elixir-wes-app:rc1
  netrcMachine: defaultmachine
  netrcLogin: defaultnetrclogin
  netrcPassword: defaultnetrcpassword


celeryWorker:
  appName: celery-worker-wes
  image: weselixir/elixir-wes-app:rc1

mongodb:
  appName: mongodb
  databaseAdminPassword: adminpasswd
  databaseName: wes-elixir-db
  databasePassword: protes-db-passwd
  databaseUser: protes-user
  volumeSize: 1Gi
  image: centos/mongodb-36-centos7

rabbitmq:
  appName: rabbitmq
  volumeSize: 1Gi
  image: rabbitmq:3-management

